import type { Metadata } from "next";
import { Roboto_Flex as Roboto } from "next/font/google";

import "../../styles/styles.css";
import "../../styles/episodes.css";
import "../../styles/footer.css";
import "../../styles/header.css";
import "../../styles/main.css";
import "@/lib/fontawesome";

import PageHeader from "@/components/header";
import PageFooter from "@/components/footer";
import Salvation from "@/components/salvation";
import { PlayerProvider } from "./context/PlayerContext";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: "variable",
});

export const metadata: Metadata = {
  title: "Eternity Ready - Podcasts",
  description: "Generated by create next app",

  icons: {
    icon: [
      { url: "/favicon.ico" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
    ],
    apple: "/apple-touch-icon.png",
  },
  // manifest: "/site.webmanifest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.variable} `} suppressHydrationWarning>
        <PageHeader />

        <PlayerProvider>{children}</PlayerProvider>

        <Salvation />
        <PageFooter />
      </body>
    </html>
  );
}
