import type { Metadata } from "next";
import { Roboto_Flex as Roboto } from "next/font/google";
import Script from 'next/script';
import "../../styles/styles.css";
import "../../styles/episodes.css";
import "../../styles/main.css";
import "@/lib/fontawesome";

import Salvation from "@/components/salvation";
import { PlayerProvider } from "./context/PlayerContext";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: "variable",
});

export const metadata: Metadata = {
  title: "Eternity Ready - Podcasts",
  description: "Generated by create next app",

  icons: {
    icon: [
      { url: "/favicon.ico" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
    ],
    apple: "/apple-touch-icon.png",
  },
  // manifest: "/site.webmanifest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </head>
      <Script id="gtm-init" strategy="beforeInteractive">
        {`
          (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-TMFGS53Q');
        `}
      </Script>
      <body className={`${roboto.variable} `} suppressHydrationWarning>
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-TMFGS53Q"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          />
        </noscript>
        <Script src="/lib/global-exporter.js" strategy="beforeInteractive" />
        <Script src="https://eternityready.com/lib/constants.js" strategy="beforeInteractive" />
        <Script src="https://eternityready.com/lib/tracking.js" strategy="beforeInteractive" />
        <Script src="https://eternityready.com/lib/session.js" strategy="beforeInteractive" />
        <Script src="https://eternityready.com/lib/toast.js" strategy="beforeInteractive" />
        <Script src="https://eternityready.com/lib/normalize.js" strategy="beforeInteractive" />
        <Script src="https://eternityready.com/lib/media-section.js" strategy="beforeInteractive" />
        <Script src="https://eternityready.com/lib/utils.js" strategy="beforeInteractive" /> 
        <eternity-header></eternity-header>
        <PlayerProvider>{children}</PlayerProvider>
        <Salvation />
        <eternity-footer></eternity-footer>
        <Script src="https://eternityready.com/lib/eternityHeader.js" strategy="afterInteractive" />
        <Script src="https://eternityready.com/lib/eternityFooter.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
