import type { Metadata } from "next";
import { Roboto_Flex as Roboto } from "next/font/google";
import Script from 'next/script';
import "../../styles/styles.css";
import "../../styles/episodes.css";
import "../../styles/main.css";
import "@/lib/fontawesome";

import Salvation from "@/components/salvation";
import { PlayerProvider } from "./context/PlayerContext";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: "variable",
});

export const metadata: Metadata = {
  title: "Eternity Ready - Podcasts",
  description: "Generated by create next app",

  icons: {
    icon: [
      { url: "/favicon.ico" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
    ],
    apple: "/apple-touch-icon.png",
  },
  // manifest: "/site.webmanifest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.variable} `} suppressHydrationWarning>
        <Script src="/lib/global-exporter.js" strategy="beforeInteractive" />
        <Script src="https://eternityready.com/lib/constants.js" strategy="beforeInteractive" />
        <Script src="https://eternityready.com/lib/session.js" strategy="beforeInteractive" />
        <Script src="https://eternityready.com/lib/toast.js" strategy="beforeInteractive" />
        <Script src="https://eternityready.com/lib/utils.js" strategy="beforeInteractive" /> 
        <eternity-header></eternity-header>
        <PlayerProvider>{children}</PlayerProvider>
        <Salvation />
        <eternity-footer></eternity-footer>
        <Script src="https://eternityready.com/lib/eternityHeader.js" strategy="afterInteractive" />
        <Script src="https://eternityready.com/lib/eternityFooter.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
